version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/usr/share/nginx/html
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/letsencrypt
      - ./:/app
      - ./data:/data
      - /etc/letsencrypt/live/slashed-project.fr/fullchain.pem:/etc/letsencrypt/live/slashed-project.fr/fullchain.pem:ro
      - /etc/letsencrypt/live/slashed-project.fr/privkey.pem:/etc/letsencrypt/live/slashed-project.fr/privkey.pem:ro
    restart: unless-stopped

  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    restart: unless-stopped

volumes:
  db_data: