version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/letsencrypt
      - /etc/letsencrypt/live/slashed-project.fr/fullchain.pem:/etc/letsencrypt/live/slashed-project.fr/fullchain.pem:ro
      - /etc/letsencrypt/live/slashed-project.fr/privkey.pem:/etc/letsencrypt/live/slashed-project.fr/privkey.pem:ro
    restart: unless-stopped