version: '3.8'
services:
  server:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - slashed-network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: slashed_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - slashed-network

networks:
  slashed-network:

volumes:
  db_data: